### ISSUE TITLE
Pas de modules

### ISSUE THREAD

**Issue by ValWasBetter** [EmmanuelDevM/Delta#2]
Bonjour, tu as oublié le fichier package, donc on peux pas installer les modules

**Comment by Emmanuel-Novus-zz** [comment]
Bonjour,
Je suis désolé pour l'attente.
Vous pouvez faire la commande `node index.js` qui vous retournera plusieurs erreurs sur des modules manquants. Ainsi, installer ces modules.
Cordialement,
Emmanuel
